-- MySQL Script generated by MySQL Workbench
-- Fri Feb 26 11:58:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sequelizeRegister
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sequelizeRegister
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sequelizeRegister` DEFAULT CHARACTER SET utf8 ;
USE `sequelizeRegister` ;

-- -----------------------------------------------------
-- Table `sequelizeRegister`.`direccions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sequelizeRegister`.`direccions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `address` INT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sequelizeRegister`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sequelizeRegister`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(100) NOT NULL,
  `avatar` VARCHAR(45) NULL,
  `direccionId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_direccions_direccionId_idx` (`direccionId` ASC) VISIBLE,
  CONSTRAINT `fk_users_direccions_direccionId`
    FOREIGN KEY (`direccionId`)
    REFERENCES `sequelizeRegister`.`direccions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
